## Troubleshooting - Tasks Failed

### Sceniaro

The DAG ```lth_lab3_etl_dag``` contains four tasks that have been running successfully for an extended period. However, on 2025-02-27 at 02:25:00 UTC, the **transform** task failed during execution.

![](https://github.com/frankie-wy/els_mwaa_2025/blob/main/lab3/lab3_task_failed.png)

### Question

Please analyze the attached log files (els_lab3_logs.zip), which include worker, scheduler, and DAG processing logs, to determine the cause of the **transform** task failure.

In your response, please provide:

- The root cause of the failure
- Your analysis of the situation
- A step-by-step description of your troubleshooting approach
